### ISSUE TITLE
Hoopoo Feather Display

### ISSUE THREAD

**Issue by QueenFrau** [GnomeModder/EnforcerMod#19]
I don't know if this is the right place to put this, but here goes.

The Hoopoo feather display in version 3.2.3 is less than ideal. I appreciate the fact that it looks like Enforcer has wings, but unfortunately the 'wings' block the view of enemies by _directly blocking the area of the screen where the crosshair is._
This makes getting the Hoopoo feather a lot less desirable, which is not good for balance or aesthetics.

If the 'wings' were made smaller by about 75%, I can see the effect working much better. It could as well be humorous, such a big bulky riot dude with itty bitty wings double-jumping. 

Thank you for considering this issue, and for making a wonderful mod for RoR2!

**Comment by TheTimeSweeper** [comment]
it was a meme lol.

it's fixed. I had my fun
