### ISSUE TITLE
ATG missiles sticking to Enforcer's shield

### ISSUE THREAD

**Issue by QueenFrau** [GnomeModder/EnforcerMod#23]
Weird little bug I've noticed today.

Observed issue: ATG missiles get stuck behind the Enforcer's shield.

Steps to Reproduce: With ATG's equipped, use the shield ability and fire. When ATG's proc, there is a chance it will 'stick' to the shield and stay there until Enforcer unshields, moves left or right 'out of the way' of the missile, or the missile heads straight down and hits terrain.

Expected: ATG's fly and do the hurty on the badguys.

**Comment by TheTimeSweeper** [comment]
believe this was fixed with the other fixes to shuriken and grenades hitting shield and/or the physical shield. Props for proper bug report format 👌
