### ISSUE TITLE
Weird Enforcer movement Bug.

### ISSUE THREAD

**Issue by Coffe-e** [GnomeModder/EnforcerMod#25]
It's kinda hard to describe so I took a video of the bug. Last time I tried capturing it, it crashed when I shielded and unshielded, but obs was fucking with my comp at the time so idk if that's what caused the crash. Im currently using the latest version of Enforcer on thunderstore. (3.3.5)

The video was too big so I uploaded it to youtube.
https://www.youtube.com/watch?v=XWqs2L9eDoU

**Comment by TheTimeSweeper** [comment]
funny physical shield. fixed now
