### ISSUE TITLE
[Aetherium] + [Enforcer] Bug With Shielding Core Item

### ISSUE THREAD

**Issue by GalacticRuler** [GnomeModder/EnforcerMod#8]
the item display for Nemesis Enforcer, when given a Shielding Core (green item from Aetherium), is scaled incorrectly, making it about 6x the size of NE himself. Purely visual bug, but was worth mentioning since it disrupts gameplay when that item is on that character. This was all with the Champion skin

**Comment by MightyW0lf** [comment]
Same thing occurs with Golden Knurl from the [GoldenCoastPlus](https://thunderstore.io/package/Skell/GoldenCoastPlus/) mod:
![image](https://user-images.githubusercontent.com/30864557/117531779-927cf880-afe4-11eb-80b8-4950f7a258c9.png)

**Comment by TheTimeSweeper** [comment]
These are the result of Default item display rules. On these older characters, there's a shitty blender quirk that made their armatures 100x scale when they were exported to unity. Just fixed them on miner, they'll be fixed in the next update, whenever the hell that happens lol

**Comment by TheTimeSweeper** [comment]
oh hey I can finally close this. r2api put out an update with the ability to remove default item displays like these.
